name: Coverage report

on: [push]

# codacy
# jobs:
#   codacy-coverage-reporter:
#     runs-on: ubuntu-latest
#     name: codacy-coverage-reporter
#     steps:
#       - uses: actions/checkout@v2
#       - name: Run codacy-coverage-reporter
#         uses: codacy/codacy-coverage-reporter-action@v1
#         with:
#           project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
#           # or
#           # api-token: ${{ secrets.CODACY_API_TOKEN }}
#           coverage-reports: coverage.xml
#           # or a comma-separated list for multiple reports
#           # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'


# jobs:
#     coverage:
#         runs-on: ubuntu-latest
#         steps:
#           - name: Get Cover 
#             uses: orgoro/coverage@v3
#             with:
#                 coverageFile: coverage.xml
#                 token: ${{ secrets.GITHUB_TOKEN }}