name: Coverage report

on: [push]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Code Coverage Summary Report
#       uses: irongut/CodeCoverageSummary@v1.3.0
#       with:
#         filename: coverage.xml

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Get Cover 
            uses: orgoro/coverage@v3
            with:
                coverageFile: coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}